# List of standard library specs that run on the wasm32-wasi target.
#
# Originally generated by `spec/generate_wasm32_spec.sh`; curated by hand since
# 2026-09-10 (see WASM_PLAN.md). Annotations on disabled specs:
#
# * `failed codegen`: the spec doesn't compile. Most are `expect_raises`
#   returning `Nil` because exceptions aren't implemented on wasm32 yet, or
#   APIs that don't exist in WASI (processes, threads, signals, OpenSSL).
# * `failed linking`: needs a library that isn't available (libLLVM).
# * `failed to run`: compiles but fails at run time (fibers, GC, exceptions,
#   missing WASI functionality).
#
# Specs that need a third-party library are guarded with a `without_*` flag so
# the harness can run with only wasi-libc + pcre2 (as CI does) or with the
# libraries built by `scripts/wasm32/build-libs.sh`.

require "./std/array_spec.cr"
require "./std/atomic_spec.cr"
require "./std/base64_spec.cr"
require "./std/benchmark_spec.cr"
{% unless flag?(:without_gmp) %}
  require "./std/big/big_decimal_spec.cr"
  require "./std/big/big_float_spec.cr"
  require "./std/big/big_int_spec.cr"
  require "./std/big/big_rational_spec.cr"
{% end %}
require "./std/big/number_spec.cr"
require "./std/bit_array_spec.cr"
require "./std/bool_spec.cr"
require "./std/box_spec.cr"
# require "./std/channel_spec.cr" (failed to run)
require "./std/char/reader_spec.cr"
require "./std/char_spec.cr"
require "./std/class_spec.cr"
require "./std/colorize_spec.cr"
require "./std/comparable_spec.cr"
require "./std/complex_spec.cr"
{% unless flag?(:without_zlib) %}
  require "./std/compress/deflate/deflate_spec.cr"
  require "./std/compress/gzip/gzip_spec.cr"
  require "./std/compress/zip/zip_file_spec.cr"
  require "./std/compress/zip/zip_spec.cr"
  require "./std/compress/zlib/reader_spec.cr"
  require "./std/compress/zlib/stress_spec.cr"
  require "./std/compress/zlib/writer_spec.cr"
{% end %}
# require "./std/concurrent/select_spec.cr" (failed to run)
# require "./std/concurrent_spec.cr" (failed to run)
require "./std/crypto/bcrypt/base64_spec.cr"
require "./std/crypto/bcrypt/password_spec.cr"
require "./std/crypto/bcrypt_spec.cr"
require "./std/crypto/blowfish_spec.cr"
require "./std/crypto/subtle_spec.cr"
require "./std/crystal/compiler_rt/ashlti3_spec.cr"
require "./std/crystal/compiler_rt/ashrti3_spec.cr"
require "./std/crystal/compiler_rt/divmod128_spec.cr"
require "./std/crystal/compiler_rt/fixint_spec.cr"
require "./std/crystal/compiler_rt/float_spec.cr"
require "./std/crystal/compiler_rt/lshrti3_spec.cr"
require "./std/crystal/compiler_rt/mulodi4_spec.cr"
require "./std/crystal/compiler_rt/mulosi4_spec.cr"
require "./std/crystal/compiler_rt/muloti4_spec.cr"
require "./std/crystal/compiler_rt/multi3_spec.cr"
require "./std/crystal/compiler_rt/powidf2_spec.cr"
require "./std/crystal/compiler_rt/powisf2_spec.cr"
require "./std/crystal/digest/md5_spec.cr"
require "./std/crystal/digest/sha1_spec.cr"
# require "./std/crystal/dwarf/reader_spec.cr" (failed codegen)
# require "./std/crystal/event_loop/polling/arena_spec.cr" (failed to run)
# require "./std/crystal/event_loop/polling/poll_descriptor_spec.cr" (failed to run)
# require "./std/crystal/event_loop/polling/waiters_spec.cr" (failed to run)
require "./std/crystal/event_loop/timers_spec.cr"
# require "./std/crystal/fd_lock_spec.cr" (failed to run)
{% unless flag?(:without_gmp) %}
  require "./std/crystal/hasher_spec.cr"
{% end %}
# require "./std/crystal/lock_spec.cr" (failed to run)
require "./std/crystal/lru_cache_spec.cr"
require "./std/crystal/pointer_linked_list_spec.cr"
require "./std/crystal/pointer_pairing_heap_spec.cr"
# require "./std/crystal/syntax_highlighter/colorize_spec.cr" (failed to run)
# require "./std/crystal/syntax_highlighter/html_spec.cr" (failed to run)
require "./std/crystal/system/cpucount_spec.cr"
# require "./std/crystal/system_spec.cr" (failed to run)
require "./std/csv/csv_build_spec.cr"
require "./std/csv/csv_lex_spec.cr"
require "./std/csv/csv_parse_spec.cr"
require "./std/csv/csv_spec.cr"
require "./std/deque_spec.cr"
{% unless flag?(:without_zlib) %}
  require "./std/digest/adler32_spec.cr"
  require "./std/digest/crc32_spec.cr"
{% end %}
# require "./std/digest/io_digest_spec.cr" (failed codegen)
# require "./std/digest/md5_spec.cr" (failed codegen)
# require "./std/digest/sha1_spec.cr" (failed codegen)
# require "./std/digest/sha256_spec.cr" (failed codegen)
# require "./std/digest/sha512_spec.cr" (failed codegen)
# require "./std/dir_spec.cr" (failed codegen)
require "./std/double_spec.cr"
require "./std/ecr/ecr_lexer_spec.cr"
# require "./std/ecr/ecr_spec.cr" (failed codegen)
require "./std/enum_spec.cr"
require "./std/enumerable_spec.cr"
require "./std/env_spec.cr"
require "./std/errno_spec.cr"
# require "./std/exception/call_stack_spec.cr" (failed codegen)
# require "./std/exception_spec.cr" (failed codegen)
# require "./std/fiber/execution_context/global_queue_spec.cr" (failed to run)
# require "./std/fiber/execution_context/parallel_spec.cr" (failed to run)
# require "./std/fiber/execution_context/runnables_spec.cr" (failed to run)
require "./std/fiber/list_spec.cr"
# require "./std/fiber_spec.cr" (failed to run)
require "./std/file/match-fast-glob_spec.cr"
require "./std/file/match_spec.cr"
# require "./std/file/tempfile_spec.cr" (failed to run)
# require "./std/file_spec.cr" (failed codegen)
# require "./std/file_utils_spec.cr" (failed codegen)
require "./std/float_printer/diy_fp_spec.cr"
require "./std/float_printer/grisu3_spec.cr"
require "./std/float_printer/hexfloat_spec.cr"
require "./std/float_printer/ieee_spec.cr"
# require "./std/float_printer/ryu_printf_spec.cr" (failed to run)
require "./std/float_printer/shortest_spec.cr"
require "./std/float_spec.cr"
require "./std/gc_spec.cr"
require "./std/hash_spec.cr"
require "./std/html_spec.cr"
# require "./std/http/chunked_content_spec.cr" (failed to run)
# require "./std/http/client/client_spec.cr" (failed codegen)
{% unless flag?(:without_zlib) %}
  require "./std/http/client/response_spec.cr"
{% end %}
require "./std/http/cookie_spec.cr"
require "./std/http/cookies_spec.cr"
require "./std/http/formdata/builder_spec.cr"
# require "./std/http/formdata/parser_spec.cr" (failed codegen)
# require "./std/http/formdata_spec.cr" (failed codegen)
require "./std/http/headers_spec.cr"
# require "./std/http/http_spec.cr" (failed to run)
require "./std/http/params_spec.cr"
# require "./std/http/request_spec.cr" (failed codegen)
# require "./std/http/server/handlers/compress_handler_spec.cr" (failed codegen)
# require "./std/http/server/handlers/error_handler_spec.cr" (failed codegen)
# require "./std/http/server/handlers/handler_spec.cr" (failed codegen)
# require "./std/http/server/handlers/log_handler_spec.cr" (failed codegen)
# require "./std/http/server/handlers/static_file_handler_spec.cr" (failed codegen)
# require "./std/http/server/handlers/websocket_handler_spec.cr" (failed codegen)
# require "./std/http/server/request_processor_spec.cr" (failed codegen)
# require "./std/http/server/response_spec.cr" (failed codegen)
# require "./std/http/server/server_spec.cr" (failed codegen)
require "./std/http/status_spec.cr"
# require "./std/http/web_socket_spec.cr" (failed codegen)
{% unless flag?(:without_gmp) %}
  require "./std/humanize_spec.cr"
{% end %}
require "./std/indexable/mutable_spec.cr"
require "./std/indexable_spec.cr"
require "./std/ini_spec.cr"
{% unless flag?(:without_gmp) %}
  require "./std/int_spec.cr"
{% end %}
require "./std/io/argf_spec.cr"
require "./std/io/buffered_spec.cr"
require "./std/io/byte_format_spec.cr"
require "./std/io/delimited_spec.cr"
# require "./std/io/file_descriptor_spec.cr" (failed codegen)
# require "./std/io/hexdump_spec.cr" (failed to run)
# require "./std/io/io_spec.cr" (failed linking)
# require "./std/io/memory_spec.cr" (failed to run)
require "./std/io/multi_writer_spec.cr"
require "./std/io/prefix_suffix_buffer_spec.cr"
require "./std/io/sized_spec.cr"
# require "./std/io/stapled_spec.cr" (failed to run)
require "./std/iterator_spec.cr"
{% unless flag?(:without_yaml) %}
  require "./std/json/any_spec.cr"
{% end %}
require "./std/json/builder_spec.cr"
require "./std/json/lexer_spec.cr"
require "./std/json/parser_spec.cr"
# require "./std/json/pull_parser_spec.cr" (failed to run)
# require "./std/json/serializable_spec.cr" (failed codegen)
# require "./std/json/serialization_spec.cr" (failed codegen)
# require "./std/kernel_spec.cr" (failed codegen)
require "./std/levenshtein_spec.cr"
# require "./std/llvm/llvm_spec.cr" (failed linking)
# require "./std/llvm/type_spec.cr" (failed linking)
require "./std/log/broadcast_backend_spec.cr"
# require "./std/log/builder_spec.cr" (failed to run)
# require "./std/log/context_spec.cr" (failed to run)
# require "./std/log/dispatch_spec.cr" (failed to run)
require "./std/log/env_config_spec.cr"
# require "./std/log/format_spec.cr" (failed codegen)
# require "./std/log/io_backend_spec.cr" (failed to run)
require "./std/log/log_spec.cr"
require "./std/log/main_spec.cr"
require "./std/log/metadata_spec.cr"
require "./std/log/spec_spec.cr"
require "./std/math_spec.cr"
require "./std/mime/media_type_spec.cr"
# require "./std/mime/multipart/builder_spec.cr" (failed codegen)
# require "./std/mime/multipart/parser_spec.cr" (failed codegen)
# require "./std/mime/multipart_spec.cr" (failed codegen)
require "./std/mime_spec.cr"
# require "./std/mutex_spec.cr" (failed to run)
require "./std/named_tuple_spec.cr"
# require "./std/number_spec.cr" (failed to run)
# require "./std/oauth/access_token_spec.cr" (failed codegen)
# require "./std/oauth/authorization_header_spec.cr" (failed codegen)
# require "./std/oauth/consumer_spec.cr" (failed codegen)
# require "./std/oauth/request_token_spec.cr" (failed codegen)
# require "./std/oauth/signature_spec.cr" (failed codegen)
# require "./std/oauth2/access_token_spec.cr" (failed codegen)
# require "./std/oauth2/client_spec.cr" (failed codegen)
# require "./std/oauth2/session_spec.cr" (failed codegen)
# require "./std/object_spec.cr" (failed to run)
# require "./std/openssl/cipher_spec.cr" (failed codegen)
# require "./std/openssl/digest_spec.cr" (failed codegen)
# require "./std/openssl/hmac_spec.cr" (failed codegen)
# require "./std/openssl/pkcs5_spec.cr" (failed codegen)
# require "./std/openssl/ssl/context_spec.cr" (failed codegen)
# require "./std/openssl/ssl/hostname_validation_spec.cr" (failed codegen)
# require "./std/openssl/ssl/ktls_spec.cr" (failed codegen)
# require "./std/openssl/ssl/server_spec.cr" (failed codegen)
# require "./std/openssl/ssl/socket_spec.cr" (failed codegen)
# require "./std/openssl/x509/certificate_spec.cr" (failed codegen)
# require "./std/openssl/x509/name_spec.cr" (failed codegen)
require "./std/option_parser_spec.cr"
require "./std/path_spec.cr"
require "./std/pointer/appender_spec.cr"
require "./std/pointer_spec.cr"
require "./std/pp_spec.cr"
require "./std/pretty_print_spec.cr"
require "./std/proc_spec.cr"
require "./std/process/exit_reason_spec.cr"
# require "./std/process/find_executable_spec.cr" (failed to run)
# require "./std/process/status_spec.cr" (failed codegen)
require "./std/process/utils_spec.cr"
require "./std/process_spec.cr"
# require "./std/raise_spec.cr" (failed codegen)
require "./std/random/isaac_spec.cr"
require "./std/random/pcg32_spec.cr"
require "./std/random/secure_spec.cr"
{% unless flag?(:without_gmp) %}
  require "./std/random_spec.cr"
{% end %}
# require "./std/range_spec.cr" (failed to run)
require "./std/record_spec.cr"
# require "./std/reference_spec.cr" (failed to run)
require "./std/regex/match_data_spec.cr"
require "./std/regex_spec.cr"
require "./std/semantic_version_spec.cr"
require "./std/set_spec.cr"
require "./std/signal_spec.cr"
require "./std/slice_spec.cr"
# require "./std/socket/address_spec.cr" (failed codegen)
# require "./std/socket/addrinfo_spec.cr" (failed to run)
# require "./std/socket/socket_spec.cr" (failed codegen)
require "./std/socket/tcp_server_spec.cr"
require "./std/socket/tcp_socket_spec.cr"
# require "./std/socket/udp_socket_spec.cr" (failed to run)
# require "./std/socket/unix_server_spec.cr" (failed codegen)
# require "./std/socket/unix_socket_spec.cr" (failed codegen)
require "./std/spec/context_spec.cr"
require "./std/spec/expectations_spec.cr"
require "./std/spec/filters_spec.cr"
require "./std/spec/helpers/iterate_spec.cr"
# require "./std/spec/hooks_spec.cr" (failed codegen)
# require "./std/spec/junit_formatter_spec.cr" (failed to run)
# require "./std/spec/list_tags_spec.cr" (failed codegen)
require "./std/spec/tap_formatter_spec.cr"
# require "./std/spec_spec.cr" (failed codegen)
{% unless flag?(:without_gmp) %}
  require "./std/sprintf_spec.cr"
{% end %}
require "./std/static_array_spec.cr"
require "./std/string/grapheme_break_spec.cr"
require "./std/string/grapheme_spec.cr"
require "./std/string/utf16_spec.cr"
require "./std/string_builder_spec.cr"
require "./std/string_pool_spec.cr"
require "./std/string_scanner_spec.cr"
require "./std/string_spec.cr"
{% unless flag?(:without_gmp) %}
  require "./std/struct_spec.cr"
{% end %}
require "./std/symbol_spec.cr"
# require "./std/sync/condition_variable_spec.cr" (failed to run)
# require "./std/sync/exclusive_spec.cr" (failed to run)
# require "./std/sync/mutex_spec.cr" (failed to run)
# require "./std/sync/rw_lock_spec.cr" (failed to run)
# require "./std/sync/shared_spec.cr" (failed to run)
require "./std/syscall_spec.cr"
# require "./std/system/group_spec.cr" (failed to run)
# require "./std/system/user_spec.cr" (failed to run)
require "./std/system_error_spec.cr"
# require "./std/system_spec.cr" (failed codegen)
# require "./std/thread/condition_variable_spec.cr" (failed codegen)
# require "./std/thread/mutex_spec.cr" (failed codegen)
# require "./std/thread_spec.cr" (failed codegen)
require "./std/time/custom_formats_spec.cr"
require "./std/time/format_spec.cr"
require "./std/time/instant_spec.cr"
require "./std/time/location_spec.cr"
require "./std/time/span_spec.cr"
require "./std/time/time_spec.cr"
require "./std/tuple_spec.cr"
require "./std/uint_spec.cr"
require "./std/uri/json_spec.cr"
require "./std/uri/params/from_www_form_spec.cr"
require "./std/uri/params/serializable_spec.cr"
require "./std/uri/params/to_www_form_spec.cr"
require "./std/uri/params_spec.cr"
require "./std/uri/punycode_spec.cr"
{% unless flag?(:without_yaml) %}
  require "./std/uri_spec.cr"
{% end %}
require "./std/uuid/json_spec.cr"
{% unless flag?(:without_yaml) %}
  require "./std/uuid/yaml_spec.cr"
{% end %}
require "./std/uuid_spec.cr"
# require "./std/va_list_spec.cr" (failed codegen)
# require "./std/wait_group_spec.cr" (failed to run)
# require "./std/weak_ref_spec.cr" (failed to run)
require "./std/winerror_spec.cr"
{% unless flag?(:without_libxml2) %}
  require "./std/xml/builder_spec.cr"
  require "./std/xml/html_spec.cr"
  require "./std/xml/reader_spec.cr"
  require "./std/xml/xml_spec.cr"
  require "./std/xml/xpath_spec.cr"
{% end %}
{% unless flag?(:without_yaml) %}
  require "./std/yaml/any_spec.cr"
  require "./std/yaml/builder_spec.cr"
  require "./std/yaml/nodes/builder_spec.cr"
  require "./std/yaml/nodes/parser_spec.cr"
{% end %}
# require "./std/yaml/schema/core_spec.cr" (failed to run)
{% unless flag?(:without_yaml) %}
  require "./std/yaml/schema/fail_safe_spec.cr"
{% end %}
# require "./std/yaml/serializable_spec.cr" (failed codegen)
# require "./std/yaml/serialization_spec.cr" (failed codegen)
# require "./std/yaml/yaml_pull_parser_spec.cr" (failed codegen)
# require "./std/yaml/yaml_spec.cr" (failed to run)
